version: "3.8"

services:
  api1:
    build: ./app
    container_name: rinha-api1
    expose:
      - "8000"
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "160M"

  api2:
    build: ./app
    container_name: rinha-api2
    expose:
      - "8000"
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "160M"

  nginx:
    image: nginx:latest
    container_name: rinha-nginx
    ports:
      - "9999:9999"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    deploy:
      resources:
        limits:
          cpus: "0.10"
          memory: "30M"
