worker_processes auto;

events {
    worker_connections 1024;
}

http {
    access_log off;
    
    upstream backend_apis {
        server api1:8000;
        server api2:8000;
        
        keepalive 100;
    }

    server {
        listen 9999;

        location / {
            proxy_pass http://backend_apis;
            proxy_http_version 1.1;
            proxy_set_header Connection "";
        }
    }
}